#!/bin/bash

#Change * to files location, does file command on everyfile and counts how many of each type there are

file * > temp.txt
types = (Zip ASCII MS-DOS data HTML PE32)
for type in types
do
  grep  "$type" temp.txt | wc -l
done

