#!/bin/bash

datafile="/mnt/data.csv"

for file in /mnt/ransom/*
do
  sudo chmod 777 "$file"   #Make sure we have all needed privilges on each file, or just run as root...
  output="$(sudo pecheck.py "$file")"
  echo -n malware >> "$datafile"  #identifies for each line
  echo -n "," >> "$datafile"  #dataprocessing ","
  echo "$output" | grep -ci -E "\.dll\." >> "$datafile"  #Count Dll numbers and outputs
done

sed -i '/,0/ d' /mnt/data.csv  #Removes 0 values from dll, caused trying to PE header check non PE files
