#!/bin/bash

datafile="/mnt/data.csv"

for file in /mnt/ransom/*
do
  sudo chmod 777 "$file"   #Make sure we have all needed privilges on each file, or just run as root...
  output="$(sudo pecheck.py "$file")" #make variable for faster processing
  #DLL count
  echo -n malware >> "$datafile"  #identifies for each line
  echo -n "," >> "$datafile"  #dataprocessing ","
  echo -n "$output" | grep -ci -E "\.dll\." | tr -d '\n' >> "$datafile"  #Count Dll numbers and outputs
  #MajorLinkerVersion
  echo -n "," >> "$datafile"
  hexvalue="$(echo -n "$output" | grep MajorLinkerVersion | awk '{print $4}' | sed -r 's/^.{2}//' | tr -d '\n')"
  echo "ibase=16; "$hexvalue"" | bc | tr -d '\n' >> "$datafile"
  #MajorImageVersion
  echo -n "," >> "$datafile"
  hexvalue2="$(echo -n "$output" | grep MajorImageVersion | awk '{print $4}' | sed -r 's/^.{2}//' | tr -d '\n')"
  echo "ibase=16; "$hexvalue2"" | bc >> "$datafile"

done

sed -i '/,0/ d' "$datafile" #Removes 0 values from dll, caused trying to PE header check non PE files

